server:
  port: 8083

#spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017
#      database: microServicesUHR

spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/microserviceUHR
      username: postgres 
      password: root
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
      
      
  application:
    name: RETING-SERVICE
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka